apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ecolink
  source:
    repoURL: https://github.com/DOAN2-UQT-KN/helm.git
    targetRevision: main
    path: charts/api-gateway
    helm:
      releaseName: api-gateway
      valuesObject:
        image:
          repository: uqtri/api-gateway
          tag: 20260419-091513-9c8cc51
        ingress:
          enabled: true
          className: traefik
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: api.ecolink.id.vn
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - api.ecolink.id.vn
              secretName: ecolink-api-tls
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
