apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecolink-fe
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ecolink
  source:
    repoURL: https://github.com/DOAN2-UQT-KN/helm.git
    targetRevision: main
    path: charts/frontend
    helm:
      releaseName: ecolink-fe
      valuesObject:
        image:
          repository: uqtri/ecolink-fe
          tag: 20260218-154648-6c2c439
        replicaCount: 1
        autoscaling:
          enabled: true
          minReplicas: 1
          maxReplicas: 10
          targetCPUUtilizationPercentage: 80
          targetMemoryUtilizationPercentage: 80
        ingress:
          enabled: true
          className: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: ecolink.id.vn
              paths:
                - path: /
                  pathType: Prefix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
