apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-postgis
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: ecolink

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: "15.5.38"

    helm:
      releaseName: postgres-postgis
      valuesObject:
        architecture: standalone

        auth:
          postgresPassword: password

        primary:
          initdb:
            scripts:
              init.sql: |
                CREATE DATABASE identitydb;
                CREATE DATABASE monolith_db;

                \connect identitydb
                CREATE EXTENSION IF NOT EXISTS postgis;

                \connect monolith_db
                CREATE EXTENSION IF NOT EXISTS postgis;

          persistence:
            enabled: true
            size: 5Gi

        service:
          type: ClusterIP
          ports:
            postgresql: 5432

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
