apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-postgis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ecolink

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: "15.5.38"

    helm:
      releaseName: postgres-postgis
      valuesObject:
        architecture: standalone

        image:
          registry: docker.io
          repository: postgis/postgis
          tag: "17-3.5"

        auth:
          postgresPassword: password

        primary:
          initdb:
            scripts:
              01-create-databases-and-postgis.sql: |
                SELECT 'CREATE DATABASE identitydb'
                WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'identitydb')\gexec

                SELECT 'CREATE DATABASE monolith_db'
                WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'monolith_db')\gexec

                \connect identitydb
                CREATE EXTENSION IF NOT EXISTS postgis;

                \connect monolith_db
                CREATE EXTENSION IF NOT EXISTS postgis;

          persistence:
            enabled: true
            size: 5Gi

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi

        service:
          ports:
            postgresql: 5432

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
