apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-postgis
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: ecolink

  source:
    repoURL: https://github.com/DOAN2-UQT-KN/helm.git
    targetRevision: main
    path: charts/postgres-postgis

    helm:
      releaseName: postgres-postgis
      valuesObject:
        image:
          repository: postgis/postgis
          tag: "17-3.5"
        auth:
          password: password
        databases:
          - identitydb
          - incidentdb
          - rewarddb
          - notificationdb
          - monolith_db
        persistence:
          enabled: true
          size: 20Gi
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        service:
          type: ClusterIP
          port: 5432
        ingress:
          enabled: false
        tcpIngress:
          enabled: true
          entryPoints:
            - postgresql
          hostSNI: db.ecolink.id.vn
          tls:
            enabled: false
            passthrough: false

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
