apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reward-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ecolink
  source:
    repoURL: https://github.com/DOAN2-UQT-KN/helm.git
    targetRevision: main
    path: charts/reward-service
    helm:
      releaseName: reward-service
      valuesObject:
        image:
          repository: uqtri/reward-service
          tag: 20260428-063930-e74aa65
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
